### PR TITLE
feat(lifecycle): get pull assets and primed stage packages

### PR DESCRIPTION
**Pull request by cmatsuoka**
Add methods to the lifecycle service to retrieve the list of pull
assets and primed stage packages from a given part. These can be
used to generate manifests of processed content.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

- [x] Have you followed the guidelines for contributing?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `tox`?

-----

### CODE REVIEW

**Comment by cmatsuoka** [comment]
This is being tested with Snapcraft in https://github.com/canonical/snapcraft/pull/4611.

**Review by mr-cal — COMMENTED** [review]
This looks fine but the snapcraft test branch for this PR is failing (it looks like a missing import is preventing the tests from running).

**Comment by cmatsuoka** [comment]
> This looks fine but the snapcraft test branch for this PR is failing (it looks like a missing import is preventing the tests from running).

Snapcraft test branch updated (it was missing a commit) and fixed.

**Review by mr-cal — APPROVED** [review]
Thanks!  I see the snapcraft tests `manifest/manifest-creation:envvars` and `manifest/manifest-info-envvars` are passing now!

**Comment by cmatsuoka** [comment]
Rebased on main.

**Review by lengau — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
