### PR TITLE
docs(changelog): add 3.1.0 release notes

### PR DESCRIPTION
**Pull request by mr-cal**
- [x] Have you followed the guidelines for contributing?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox`?

-----

Unblocks https://github.com/canonical/snapcraft/issues/4889
Unblocks https://github.com/canonical/snapcraft/pull/4892

### CODE REVIEW

**Review by tigarmo — APPROVED** [review]
This is going to conflict with #376 ; I suggest we merge that one first so that 3.1.0 gets the features from 2.9.0

**Comment by mr-cal** [comment]
Agreed!

**Comment by tigarmo** [comment]
Nice! Then maybe add a note to say that 3.1.0 incorporates the features from 2.9.0?

**Comment by mr-cal** [comment]
I've always wondered if the release notes should describe when hotfixes on older versions are brought into the latest release.  I'll add a note.

**Comment by tigarmo** [comment]
In this particular case where we did things non-linearly I suggest doing this for our own future sakes

**Review by dariuszd21 — APPROVED** [review]

**Comment by mr-cal** [comment]
Need to check with @tigarmo if he is ordering the changelog by version or date

**Comment by tigarmo** [comment]
I think we should order it by date

**Pull request merged**
